### ISSUE TITLE
Why do you think using builtin HashMap makes it less efficient than it otherwise could be?

### ISSUE THREAD

**Issue by myarcana** [AdrienChampion/hashconsing#10]
In the introduction in the documentation it's written that

> It is probably less efficient as uses Rust’s `HashMap`s, not a custom built structure

In what way do you think it might be inefficient because of using Rust's HashMaps? What kind of custom structure would actually be ideal?

**Comment by AdrienChampion** [comment]
In the paper, they design their own bucket strategy and such, specially for what they want to do.

I read the paper (and wrote this library) a very long time ago, and wrote this bit without really thinking about it. So it might not be super relevant :/

**Comment by AdrienChampion** [comment]
@myarcana did I answer your question? If so maybe we can close this?

**Comment by myarcana** [comment]
> @myarcana did I answer your question? If so maybe we can close this?

Yes! Thank you
